---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: timeprintersRole
rules:
- apiGroups:
  - example.com
  resources:
  - timeprinters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - timeprinters/finalizers
  verbs:
  - update
- apiGroups:
  - example.com
  resources:
  - timeprinters/status
  verbs:
  - get
  - patch
  - update
