# config/crd/bases/timeprinter.example.com_timeprinters.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: timeprinters.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                intervalSeconds:
                  type: integer
                  minimum: 1
  scope: Namespaced
  names:
    plural: timeprinters
    singular: timeprinter
    kind: TimePrinter
    shortNames:
    - tp